services:
  db:
    image: postgres:17-alpine
    container_name: gopher-tasks-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gophertasks
    ports:
      - "5438:5432"       # <-- mapeia host:container
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
