server:
  port: 8080
  readtimeout: 5s
  writetimeout: 10s

database:
  driver: postgres
  dsn: "postgres://user:pass@localhost:5432/gophertasks?sslmode=disable"

auth:
  jwtsecret: "your-secret-key"
  tokenexpiryminutes: 60

log:
  level: "debug"
  format: "text"
